### ISSUE TITLE
My Loans

### ISSUE THREAD

**Issue by zackhsi** [izd/kiva#23]
Have feed in view pager for profile page showing your loans.

**Comment by BrainScraps** [comment]
@danielhochman @zackhsi - should we only show the _real_ Kiva contributions? So if a user goes through our "stubbed out" Lending flow, it won't show up there?

**Comment by zackhsi** [comment]
I believe we want to show the contribution that was just made, regardless of whether it was real or fake. Which is why faking it out feels so wrong.

**Comment by BrainScraps** [comment]
okay - for the purposes of demo day (and simplicity) we should show
"loaned" from Parse, but not take it into account when we total up the
'Loaned amount'

**Comment by BrainScraps** [comment]
sorry, I didn't intend for that to be so forceful. I think that'd be a reasonable middle ground

**Comment by zackhsi** [comment]
We should add the new loan to the total. It doesn't need to work more than
once, but the UI should reflect that a loan was just made.

**Comment by BrainScraps** [comment]
Yeah, I haven't figured out where the flow should go after a loan is paid
for. any ideas?

**Comment by BrainScraps** [comment]
That's a good point tho

**Comment by danielhochman** [comment]
I think it should go to to the profile page with the new details reflected. Maybe a cool animation where your total increases and the new loans appears at the top of the list. Kind of like when you finish a level in a game and it tallies your score.

I think this is the pattern of most apps with creation: you make a post on Facebook, Twitter, then you are taken to your profile to see it.
