### ISSUE TITLE
[CodePath Android Final Project Sprint 2] Please review

### ISSUE THREAD

**Issue by BrainScraps** [izd/kiva#35]
User stories completed: 
- Unauthenticated user can browse Loans using spinner
- User can click on Loan to see Loan Detail
- User can choose to Loan in the Loan Detail page
- User can use PayPal and Card.io to Loan
- User can login to her profile
- User can use ViewPager to view profile, Loans

![milestone](https://cloud.githubusercontent.com/assets/806101/6977794/3c886924-d97a-11e4-84a0-ff528a6c8c3b.gif)

**Comment by BrainScraps** [comment]
cc @codepath @codepathreview

**Comment by codepathreview** [comment]
:+1: Nice work so far on the group project. Your team has made great progress in the last week. Hope you are proud of what you have achieved in ~6 weeks.
- Great to see that you took actions from the review comments from Sprint 1 and created milestones/issues for sprint 2.
- :+1: Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place.
- Good to see that you have already started adding UI polish to your app, keep working hard on that
- Good job from everyone in contributing to the project, but it will be great if everyone [contributes](https://github.com/izd/kiva/graphs/contributors) equally. Hope everyone is learning and enjoying from this
- While working on polishing your app for next sprint, remember that your app follows the [android design guidelines](http://guides.codepath.com/android/Android-Design-Guidelines) and also benchmark your app on sites such as [android app patterns](http://www.android-app-patterns.com/) to improve the UI/UX.

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week!
