### ISSUE TITLE
Create model and intent for profile page

### ISSUE THREAD

**Issue by danielhochman** [izd/kiva#5]
Profile page is the page that the user can see high-level data about all loans they have funded. There will also be a list of loans funded and potentially access to favorites.

TODO:
- [x] Create new activity and launch it through menu icon
- [x] Include profile info (stubbed)
- [x] View pager

**Comment by danielhochman** [comment]
Content to consider:
https://www.kiva.org/portfolio
https://www.kiva.org/settings/account

**Comment by zackhsi** [comment]
Does this include Facebook login?

**Comment by zackhsi** [comment]
Taking it.

**Comment by BrainScraps** [comment]
Just to answer your question, I don't think this includes FB login . 

Also - I created a developer account on Kiva - LMK if you want some credentials

**Comment by zackhsi** [comment]
@BrainScraps @danielhochman I made a private group for us in Slack (codepath domain). Could you post the creds in there?
