### ISSUE TITLE
API and/or mock server

### ISSUE THREAD

**Issue by danielhochman** [izd/kiva#8]
Develop bindings for the API and/or write the JSON spec for a mock server if API is not sufficient.

**Comment by danielhochman** [comment]
Their API looks pretty bad. For example, http://api.kivaws.org/v1/loans/search.json

No image URLs available anywhere in the API that I can see. We're going to have to write our own server and either populate it periodically with curated/cached content or use it as a shim over kiva.org to scrape and reformat the content as JSON with all needed data.

**Comment by BrainScraps** [comment]
@danielhochman Image URLs aren't a problem. 

The API contains an image id that can be used to get it from their image endpoint

![image](https://cloud.githubusercontent.com/assets/631216/6754830/438d9102-cedc-11e4-954f-ac166d0d6b9e.png)

**Comment by danielhochman** [comment]
Ah missed that! Thanks

**Comment by BrainScraps** [comment]
:+1:
